### ISSUE TITLE
Regression: bluepill status no longer shows processes status

### ISSUE THREAD

**Issue by guss77** [bluepill-rb/bluepill#27]
After updating to version 0.0.69, the status command no longer shows the processes being monitored:

    # bluepill --version
    bluepill, version 0.0.68
    # bluepill wfs status
    wfs-puma(pid:89264): up
   
    resque:
      wfs-resque-0(pid:89274): up
      ...
    
    # bluepill quit
    ...
    # gem update bluepill
    ...
    # bluepill --version
    bluepill, version 0.0.69
    # bluepill load wfs.pill
    # bluepill wfs status
    
    resque:

**Comment by Roddd** [comment]
I've noticed the exact same thing.

**Comment by mgreensmith** [comment]
+1

**Comment by grodowski** [comment]
+1

**Comment by mhyllander** [comment]
[Line 57 and 58 need to switch places in group.rb] (https://github.com/bluepill-rb/bluepill/blob/master/lib/bluepill/group.rb#L57-L58)

**Comment by drh-stanford** [comment]
+1

**Comment by iroller** [comment]
+1 here

**Comment by kostya** [comment]
why you not use this https://github.com/kostya/eye? it fully replaced bluepill features.
