### ISSUE TITLE
Dependency problem with activesupport

### ISSUE THREAD

**Issue by rmldsky** [bluepill-rb/bluepill#44]
Current dependency on `activesupport` is:
 `spec.add_dependency 'activesupport', ['>= 3.2', '< 5']`
Unfortunately this causes a problem due to `activesupport 5.0.0beta2` being consider as `< 5`. During `gem install bluepill` one can get a complaint that `activesupport` now requires `Ruby >= 2.2.2`. Therefore with fresh install (without `activesupport` being installed prior to `bluepill`), this causes problems on Rubies < 2.2.2 where `bluepill` will simply not install.

**Comment by akzhan** [comment]
Oops, just released as 0.1.3
