### ISSUE TITLE
Installation of bluepill in secure production env

### ISSUE THREAD

**Issue by rafique586** [bluepill-rb/bluepill#48]
how do i install bluepill in secure production environment which is not exposed to internet, gem install bluepill is not working for me as needed dependencies are not available, any option to download full package ?.

**Comment by mikegee** [comment]
- download https://rubygems.org/downloads/bluepill-0.1.2.gem
- transfer to server somehow
- `gem install path/to/bluepill-0.1.2.gem`

**Comment by akzhan** [comment]
Also take a look at http://tomlea.co.uk/posts/gem-in-a-box/
